//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedyCouriers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryMan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryMan()
        {
            this.TransactionInfoes = new HashSet<TransactionInfo>();
        }
    
        public int delmanID { get; set; }
        public string delmanName { get; set; }
        public string delmanEmail { get; set; }
        public string delmanPass { get; set; }
        public string delmanPhone { get; set; }
        public string delmanAddress { get; set; }
        public string delmanStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionInfo> TransactionInfoes { get; set; }
    }
}
