//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedyCouriers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class receiverInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public receiverInfo()
        {
            this.OrderInfoes = new HashSet<OrderInfo>();
        }
    
        public int receiverID { get; set; }
        public string receiverName { get; set; }
        public string receiverAddress { get; set; }
        public Nullable<System.DateTime> receiveDate { get; set; }
        public string productType { get; set; }
        public Nullable<int> productPrice { get; set; }
        public string phoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderInfo> OrderInfoes { get; set; }
    }
}
